[2023-02-07 21:53:48,677] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: mysqloperator_demo.CreateTable manual__2023-02-07T21:53:47.635108+00:00 [queued]>
[2023-02-07 21:53:48,687] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: mysqloperator_demo.CreateTable manual__2023-02-07T21:53:47.635108+00:00 [queued]>
[2023-02-07 21:53:48,695] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 21:53:48,705] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-07 21:53:48,705] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-07 21:53:48,723] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): CreateTable> on 2023-02-07 21:53:47.635108+00:00
[2023-02-07 21:53:48,726] {standard_task_runner.py:52} INFO - Started process 220 to run task
[2023-02-07 21:53:48,729] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mysqloperator_demo', 'CreateTable', 'manual__2023-02-07T21:53:47.635108+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/mysqloperator.py', '--cfg-path', '/tmp/tmpii3vb8y3', '--error-file', '/tmp/tmp5s43hbxo']
[2023-02-07 21:53:48,730] {standard_task_runner.py:80} INFO - Job 2: Subtask CreateTable
[2023-02-07 21:53:48,771] {task_command.py:369} INFO - Running <TaskInstance: mysqloperator_demo.CreateTable manual__2023-02-07T21:53:47.635108+00:00 [running]> on host d588132d752c
[2023-02-07 21:53:48,836] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dezyre
AIRFLOW_CTX_DAG_ID=mysqloperator_demo
AIRFLOW_CTX_TASK_ID=CreateTable
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T21:53:47.635108+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-07T21:53:47.635108+00:00
[2023-02-07 21:53:48,836] {mysql.py:82} INFO - Executing:  CREATE TABLE datapath4.employee(empid int, empname VARCHAR(25), salary int); 
[2023-02-07 21:53:48,846] {base.py:68} INFO - Using connection ID 'mysl_conn' for task execution.
[2023-02-07 21:53:48,865] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user '***'@'172.27.0.7' (using password: YES)")
[2023-02-07 21:53:48,872] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=***operator_demo, task_id=CreateTable, execution_date=20230207T215347, start_date=20230207T215348, end_date=20230207T215348
[2023-02-07 21:53:48,881] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task CreateTable ((1045, "Access denied for user '***'@'172.27.0.7' (using password: YES)"); 220)
[2023-02-07 21:53:48,900] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-07 21:53:48,935] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
