[2023-03-05 01:50:57,206] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T01:50:56.732829+00:00 [queued]>
[2023-03-05 01:50:57,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T01:50:56.732829+00:00 [queued]>
[2023-03-05 01:50:57,213] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-05 01:50:57,214] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-05 01:50:57,215] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-05 01:50:57,224] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_ingest> on 2023-03-05 01:50:56.732829+00:00
[2023-03-05 01:50:57,227] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2023-03-05 01:50:57,230] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_ingest', 'manual__2023-03-05T01:50:56.732829+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmp1iqe695c', '--error-file', '/tmp/tmphnr4g8ba']
[2023-03-05 01:50:57,232] {standard_task_runner.py:80} INFO - Job 14: Subtask run_script_ingest
[2023-03-05 01:50:57,269] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T01:50:56.732829+00:00 [running]> on host 3e0a47356feb
[2023-03-05 01:50:57,315] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T01:50:56.732829+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T01:50:56.732829+00:00
[2023-03-05 01:50:57,317] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-05 01:50:57,319] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /Users/americocavallieri/Desktop/Apache_Airflow/Proyecto/ingest.py']
[2023-03-05 01:50:57,326] {subprocess.py:85} INFO - Output:
[2023-03-05 01:50:57,336] {subprocess.py:92} INFO - python: can't open file '/Users/americocavallieri/Desktop/Apache_Airflow/Proyecto/ingest.py': [Errno 2] No such file or directory
[2023-03-05 01:50:57,337] {subprocess.py:96} INFO - Command exited with return code 2
[2023-03-05 01:50:57,349] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-05 01:50:57,352] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_ingest, execution_date=20230305T015056, start_date=20230305T015057, end_date=20230305T015057
[2023-03-05 01:50:57,361] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task run_script_ingest (Bash command failed. The command returned a non-zero exit code 2.; 255)
[2023-03-05 01:50:57,403] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-05 01:50:57,430] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
