[2023-03-06 02:24:31,477] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: MiPrimerDag.1 manual__2023-03-06T02:24:30.821200+00:00 [queued]>
[2023-03-06 02:24:31,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: MiPrimerDag.1 manual__2023-03-06T02:24:30.821200+00:00 [queued]>
[2023-03-06 02:24:31,485] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-06 02:24:31,487] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-06 02:24:31,488] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-06 02:24:31,498] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): 1> on 2023-03-06 02:24:30.821200+00:00
[2023-03-06 02:24:31,504] {standard_task_runner.py:52} INFO - Started process 4548 to run task
[2023-03-06 02:24:31,506] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'MiPrimerDag', '1', 'manual__2023-03-06T02:24:30.821200+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/1_MiPrimerDag.py', '--cfg-path', '/tmp/tmpqq5ry7bd', '--error-file', '/tmp/tmpu8lbna5p']
[2023-03-06 02:24:31,508] {standard_task_runner.py:80} INFO - Job 45: Subtask 1
[2023-03-06 02:24:31,545] {task_command.py:369} INFO - Running <TaskInstance: MiPrimerDag.1 manual__2023-03-06T02:24:30.821200+00:00 [running]> on host 477ef5e408be
[2023-03-06 02:24:31,589] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=MiPrimerDag
AIRFLOW_CTX_TASK_ID=1
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T02:24:30.821200+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-06T02:24:30.821200+00:00
[2023-03-06 02:24:31,591] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-06 02:24:31,593] {subprocess.py:74} INFO - Running command: ['bash', '-c', None]
[2023-03-06 02:24:31,594] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 189, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 82, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-03-06 02:24:31,603] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=MiPrimerDag, task_id=1, execution_date=20230306T022430, start_date=20230306T022431, end_date=20230306T022431
[2023-03-06 02:24:31,610] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task 1 (expected str, bytes or os.PathLike object, not NoneType; 4548)
[2023-03-06 02:24:31,639] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-06 02:24:31,661] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
