[2023-03-10 02:26:38,979] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:26:18.825402+00:00 [queued]>
[2023-03-10 02:26:38,985] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:26:18.825402+00:00 [queued]>
[2023-03-10 02:26:38,986] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 02:26:38,987] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-10 02:26:38,988] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 02:26:38,997] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_transform> on 2023-03-10 02:26:18.825402+00:00
[2023-03-10 02:26:39,000] {standard_task_runner.py:52} INFO - Started process 2637 to run task
[2023-03-10 02:26:39,003] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_transform', 'manual__2023-03-10T02:26:18.825402+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpxejro2pz', '--error-file', '/tmp/tmp9spiviy7']
[2023-03-10 02:26:39,005] {standard_task_runner.py:80} INFO - Job 89: Subtask run_script_transform
[2023-03-10 02:26:39,043] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:26:18.825402+00:00 [running]> on host 477ef5e408be
[2023-03-10 02:26:39,088] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T02:26:18.825402+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-10T02:26:18.825402+00:00
[2023-03-10 02:26:39,090] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-10 02:26:39,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/Proyecto/transform.py']
[2023-03-10 02:26:39,098] {subprocess.py:85} INFO - Output:
[2023-03-10 02:27:05,710] {subprocess.py:92} INFO - ingest loaded
[2023-03-10 02:27:05,712] {subprocess.py:92} INFO - loaded adsl landing
[2023-03-10 02:27:05,714] {subprocess.py:92} INFO - transform loaded
[2023-03-10 02:27:05,716] {subprocess.py:92} INFO - loaded adsl gold
[2023-03-10 02:27:05,718] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-03-10 02:27:05,719] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/transform.py", line 33, in <module>
[2023-03-10 02:27:05,720] {subprocess.py:92} INFO -     u.create_mysql_tbl_schema(df_enunciado1, u.mysql_conn(u.mysql_engine()), 'retail', "enunciado1")
[2023-03-10 02:27:05,721] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/util/utils.py", line 49, in create_mysql_tbl_schema
[2023-03-10 02:27:05,722] {subprocess.py:92} INFO -     sql = "USE {db}; CREATE TABLE IF NOT EXISTS {tbl_name} ({tbl_cols_sql});".format(db, tbl_name, tbl_cols_sql)
[2023-03-10 02:27:05,723] {subprocess.py:92} INFO - KeyError: 'db'
[2023-03-10 02:27:05,804] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-10 02:27:05,816] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-10 02:27:05,819] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_transform, execution_date=20230310T022618, start_date=20230310T022638, end_date=20230310T022705
[2023-03-10 02:27:05,828] {standard_task_runner.py:97} ERROR - Failed to execute job 89 for task run_script_transform (Bash command failed. The command returned a non-zero exit code 1.; 2637)
[2023-03-10 02:27:05,842] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-10 02:27:05,858] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
