[2023-03-10 02:34:47,199] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:34:27.773833+00:00 [queued]>
[2023-03-10 02:34:47,206] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:34:27.773833+00:00 [queued]>
[2023-03-10 02:34:47,208] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 02:34:47,209] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-10 02:34:47,210] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 02:34:47,231] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_transform> on 2023-03-10 02:34:27.773833+00:00
[2023-03-10 02:34:47,236] {standard_task_runner.py:52} INFO - Started process 2861 to run task
[2023-03-10 02:34:47,238] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_transform', 'manual__2023-03-10T02:34:27.773833+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpdj47d_2l', '--error-file', '/tmp/tmpvbk2wf90']
[2023-03-10 02:34:47,241] {standard_task_runner.py:80} INFO - Job 95: Subtask run_script_transform
[2023-03-10 02:34:47,281] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T02:34:27.773833+00:00 [running]> on host 477ef5e408be
[2023-03-10 02:34:47,326] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T02:34:27.773833+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-10T02:34:27.773833+00:00
[2023-03-10 02:34:47,328] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-10 02:34:47,330] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/Proyecto/transform.py']
[2023-03-10 02:34:47,338] {subprocess.py:85} INFO - Output:
[2023-03-10 02:34:47,588] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-03-10 02:34:47,589] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/transform.py", line 1, in <module>
[2023-03-10 02:34:47,591] {subprocess.py:92} INFO -     from process.transform import df_categories, df_customer, df_departments, df_order_items, df_orders, df_products
[2023-03-10 02:34:47,592] {subprocess.py:92} INFO - ImportError: cannot import name 'df_categories' from 'process.transform' (/opt/***/dags/Proyecto/process/transform.py)
[2023-03-10 02:34:47,629] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-10 02:34:47,640] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-10 02:34:47,643] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_transform, execution_date=20230310T023427, start_date=20230310T023447, end_date=20230310T023447
[2023-03-10 02:34:47,652] {standard_task_runner.py:97} ERROR - Failed to execute job 95 for task run_script_transform (Bash command failed. The command returned a non-zero exit code 1.; 2861)
[2023-03-10 02:34:47,659] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-10 02:34:47,679] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
