[2023-03-05 02:08:24,841] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T02:08:24.619119+00:00 [queued]>
[2023-03-05 02:08:24,847] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T02:08:24.619119+00:00 [queued]>
[2023-03-05 02:08:24,848] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-05 02:08:24,849] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-05 02:08:24,850] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-05 02:08:24,859] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_ingest> on 2023-03-05 02:08:24.619119+00:00
[2023-03-05 02:08:24,863] {standard_task_runner.py:52} INFO - Started process 687 to run task
[2023-03-05 02:08:24,865] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_ingest', 'manual__2023-03-05T02:08:24.619119+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpk79u7zt_', '--error-file', '/tmp/tmpxam661ma']
[2023-03-05 02:08:24,867] {standard_task_runner.py:80} INFO - Job 22: Subtask run_script_ingest
[2023-03-05 02:08:24,908] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_ingest manual__2023-03-05T02:08:24.619119+00:00 [running]> on host 477ef5e408be
[2023-03-05 02:08:24,956] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T02:08:24.619119+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T02:08:24.619119+00:00
[2023-03-05 02:08:24,958] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-05 02:08:24,960] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python Proyecto/ingest.py']
[2023-03-05 02:08:24,969] {subprocess.py:85} INFO - Output:
[2023-03-05 02:08:24,978] {subprocess.py:92} INFO - python: can't open file 'Proyecto/ingest.py': [Errno 2] No such file or directory
[2023-03-05 02:08:24,980] {subprocess.py:96} INFO - Command exited with return code 2
[2023-03-05 02:08:24,991] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-05 02:08:24,995] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_ingest, execution_date=20230305T020824, start_date=20230305T020824, end_date=20230305T020824
[2023-03-05 02:08:25,004] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task run_script_ingest (Bash command failed. The command returned a non-zero exit code 2.; 687)
[2023-03-05 02:08:25,041] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-05 02:08:25,069] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
