[2023-03-10 01:14:07,493] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T01:13:47.058135+00:00 [queued]>
[2023-03-10 01:14:07,499] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T01:13:47.058135+00:00 [queued]>
[2023-03-10 01:14:07,500] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 01:14:07,501] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-10 01:14:07,502] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 01:14:07,510] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_script_transform> on 2023-03-10 01:13:47.058135+00:00
[2023-03-10 01:14:07,514] {standard_task_runner.py:52} INFO - Started process 1052 to run task
[2023-03-10 01:14:07,517] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_bash_operator', 'run_script_transform', 'manual__2023-03-10T01:13:47.058135+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bash_operator.py', '--cfg-path', '/tmp/tmpftw6i5hm', '--error-file', '/tmp/tmp4b3ggrw4']
[2023-03-10 01:14:07,518] {standard_task_runner.py:80} INFO - Job 73: Subtask run_script_transform
[2023-03-10 01:14:07,555] {task_command.py:369} INFO - Running <TaskInstance: pipeline_bash_operator.run_script_transform manual__2023-03-10T01:13:47.058135+00:00 [running]> on host 477ef5e408be
[2023-03-10 01:14:07,599] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Americo
AIRFLOW_CTX_DAG_ID=pipeline_bash_operator
AIRFLOW_CTX_TASK_ID=run_script_transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T01:13:47.058135+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-10T01:13:47.058135+00:00
[2023-03-10 01:14:07,601] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-10 01:14:07,602] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/Proyecto/transform.py']
[2023-03-10 01:14:07,609] {subprocess.py:85} INFO - Output:
[2023-03-10 01:14:36,017] {subprocess.py:92} INFO - ingest loaded
[2023-03-10 01:14:36,019] {subprocess.py:92} INFO - loaded adsl landing
[2023-03-10 01:14:36,020] {subprocess.py:92} INFO - transform loaded
[2023-03-10 01:14:36,025] {subprocess.py:92} INFO - loaded adsl gold
[2023-03-10 01:14:36,026] {subprocess.py:92} INFO - Traceback (most recent call last):
[2023-03-10 01:14:36,028] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/transform.py", line 32, in <module>
[2023-03-10 01:14:36,029] {subprocess.py:92} INFO -     u.create_mysql_tbl_schema(df_enunciado1, u.mysql_conn(u.mysql_engine()), 'retail', "enunciado1")
[2023-03-10 01:14:36,030] {subprocess.py:92} INFO -   File "/opt/***/dags/Proyecto/process/util/utils.py", line 21, in mysql_engine
[2023-03-10 01:14:36,031] {subprocess.py:92} INFO -     engine = create_engine("mysql://{0}:{1}@{2}:{3}/{4}?charset=utf8".format(user, password, host, port, database))
[2023-03-10 01:14:36,032] {subprocess.py:92} INFO -   File "<string>", line 2, in create_engine
[2023-03-10 01:14:36,033] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
[2023-03-10 01:14:36,034] {subprocess.py:92} INFO -     return fn(*args, **kwargs)
[2023-03-10 01:14:36,035] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
[2023-03-10 01:14:36,036] {subprocess.py:92} INFO -     dbapi = dialect_cls.dbapi(**dbapi_args)
[2023-03-10 01:14:36,037] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
[2023-03-10 01:14:36,038] {subprocess.py:92} INFO -     return __import__("MySQLdb")
[2023-03-10 01:14:36,039] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'MySQLdb'
[2023-03-10 01:14:36,116] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-10 01:14:36,128] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-10 01:14:36,132] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=pipeline_bash_operator, task_id=run_script_transform, execution_date=20230310T011347, start_date=20230310T011407, end_date=20230310T011436
[2023-03-10 01:14:36,140] {standard_task_runner.py:97} ERROR - Failed to execute job 73 for task run_script_transform (Bash command failed. The command returned a non-zero exit code 1.; 1052)
[2023-03-10 01:14:36,158] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-10 01:14:36,176] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
